In [1]:
import numpy as np

array_10_100 = np.arange(10, 101)
print("Array de 10 a 100>")
print(array_10_100)

array_invertido = array_10_100[::-1]
print("\nArray invertido>")
print(array_invertido)

array_3x3 = np.arange(9).reshape(3, 3)
print("\nArray 3x3 com valores de 0 a 8>")
print(array_3x3)

identidade_6x6 = np.eye(6)
print("\nArray identidade 6x6>")
print(identidade_6x6)

array_random_3x3x3 = np.random.rand(3, 3, 3)
print("\nArray aleatório 3x3x3>")
print(array_random_3x3x3)

A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

iguais_elemento_a_elemento = np.array_equal(A, B)
iguais_proximos = np.allclose(A, B)

print("\nArray A>")
print(A)
print("\nArray B>")
print(B)
print("\nArray A e B sao exatamente iguais?>", iguais_elemento_a_elemento)
print("Array A e B sao aproximadamente iguais?>", iguais_proximos)

Array de 10 a 100>
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]

Array invertido>
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]

Array 3x3 com valores de 0 a 8>
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Array identidade 6x6>
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Array ale

In [3]:
import numpy as np

dolares = np.random.randint(1, 1001, size=100)
print("Array em dólares>")
print(dolares)

taxa_conversao = 0.874413

euros = dolares * taxa_conversao

euros_arredondado = np.round(euros, 2)

print("\nArray convertido para euros>")
print(euros_arredondado)

Array em dólares>
[ 603  109  164  728  548   71  889  541  709  909  895  929  571  241
   71  804   18  275  940  399  991  104  492  768  599  222  846  668
  971  894  736   35  196  767  410  652    9  625  962  178  867  476
  751  325  523  131  619   22  144  514  310  725  805    7  142  932
  356  466  479  835  462   47  534  217  314  505  545  555  154  537
  842  671  749  128  594  474  816  384  360  543  760  490  830  529
  869  281  246  251  413  643  471  557  675  487  907  991  709 1000
  633  469]

Array convertido para euros>
[527.27  95.31 143.4  636.57 479.18  62.08 777.35 473.06 619.96 794.84
 782.6  812.33 499.29 210.73  62.08 703.03  15.74 240.46 821.95 348.89
 866.54  90.94 430.21 671.55 523.77 194.12 739.75 584.11 849.06 781.73
 643.57  30.6  171.38 670.67 358.51 570.12   7.87 546.51 841.19 155.65
 758.12 416.22 656.68 284.18 457.32 114.55 541.26  19.24 125.92 449.45
 271.07 633.95 703.9    6.12 124.17 814.95 311.29 407.48 418.84 730.13
 403.98  41.1  46

In [ ]:
import pandas as pd

df_titulos = pd.read_csv('05_05_imdb_titulos.csv')
print("Primeiros 5 registros de títulos>")
print(df_titulos.head())

df_elencos = pd.read_csv('05_05_imdb_elenco.csv')
print("\nPrimeiros 5 registros de elencos>")
print(df_elencos.head())

print("\nNumero de registros do dataframe de titulos>", len(df_titulos))

print("\nNumero de registros do dataframe de elencos>", len(df_elencos))

df_titulos_mais_antigos = df_titulos.sort_values(by='year').head(5)
print("\n5 titulos mais antigos")
print(df_titulos_mais_antigos[['title', 'year']])

dracula_filmes = df_titulos[df_titulos['title'].str.contains('dracula', case=False, na=False)]
print("\nFilmes que contem 'Drácula' no título>")
print(dracula_filmes[['title', 'year']])

print("\nNumeros de filmes que contem 'Drácula' no titulo>", len(dracula_filmes))

titulos_mais_comuns = df_titulos['title'].value_counts().head(10)
print("\n10 Títulos mais comuns:")
print(titulos_mais_comuns)

romeo_juliet_filmes = df_titulos[df_titulos['title'].str.contains('romeo', case=False, na=False) & 
                                  df_titulos['title'].str.contains('juliet', case=False, na=False)]

print("\nFilmes com 'Romeo' e 'Juliet' no título:")
print(romeo_juliet_filmes.sort_values(by='year')[['title', 'year']])

In [30]:
exorcist_filmes = df_titulos[df_titulos['title'].str.contains('Exorcist', case=False, na=False)].sort_values('year')
print(exorcist_filmes)

                                         title  year
88003                             The Exorcist  1973
49658                  O Exorcista de Mulheres  1974
118920     Satanico Pandemonium: La Sexorcista  1975
140519                Exorcist II: The Heretic  1977
220073                        Kung Fu Exorcist  1978
17375                         The Exorcist III  1990
132451                        Teenage Exorcist  1991
117797                 Exorcist: The Beginning  2004
94189        Dominion: Prequel to the Exorcist  2005
209250  Costa Chica: Confession of an Exorcist  2006
86354                      Exorcist Chronicles  2007
130686                      The Disco Exorcist  2011
57932                      Exorcist Chronicles  2013
69974                           Shark Exorcist  2015
51101                            Bad Exorcists  2015
151850                              Exorcistas  2015
60700                      Accidental Exorcist  2016
161093                       American Exorcist

In [32]:
filmes_1950 = df_titulos[df_titulos['year'] == 1950]
print(len(filmes_1950))

1081


In [34]:
filmes_anos_50 = df_titulos[(df_titulos['year'] >= 1950) & (df_titulos['year'] <= 1959)]
print(len(filmes_anos_50))

12606


In [46]:
godfather_filmes = df_elencos[df_elencos['title'].str.contains('The Godfather', case=False, na=False)]
papel_contagem = godfather_filmes.groupby('character').size().reset_index(name='quantidade')
papel_contagem = papel_contagem.sort_values('quantidade', ascending=False)
print(papel_contagem)

            character  quantidade
72              Extra           5
0             Al Neri           2
196   Sandra Corleone           2
229     Theresa Hagen           2
228            Tessio           2
..                ...         ...
95              Fredo           1
97       Fruit Vendor           1
98              Genco           1
99               Gesu           1
261  Zasa's Bodyguard           1

[262 rows x 2 columns]


In [50]:
dracula_1958 = df_elencos[(df_elencos['title'].str.contains('dracula', case=False, na=False)) & (df_elencos['year'] == 1958)]
dracula_1958_sorted = dracula_1958.sort_values('n')
print(dracula_1958_sorted)

                         title  year                   name     type  \
485197                 Dracula  1958          Peter Cushing    actor   
1240853  The Return of Dracula  1958        Francis Lederer    actor   
2705228  The Return of Dracula  1958        Norma Eberhardt  actress   
1242307                Dracula  1958        Christopher Lee    actor   
1242308                Dracula  1958        Christopher Lee    actor   
2091208  The Return of Dracula  1958          Ray Stricklyn    actor   
822398                 Dracula  1958          Michael Gough    actor   
3410427                Dracula  1958      Melissa Stribling  actress   
2306094  The Return of Dracula  1958           John Wengraf    actor   
3069196                Dracula  1958            Carol Marsh  actress   
3489498  The Return of Dracula  1958       Virginia Vincent  actress   
408463   The Return of Dracula  1958            Gage Clarke    actor   
2677557                Dracula  1958            Olga Dickie  act

In [52]:
bruce_wayne_roles = df_elencos[(df_elencos['character'].str.contains('Bruce wayne', case=False , na=False)) & (df_elencos['n'] == 1)]
print(len(bruce_wayne_roles))

20


In [56]:
deniro_roles = df_elencos[df_elencos['name'].str.contains('Robert De Niro', case=False)]
print(len(deniro_roles))

103


In [60]:
heston_60s = df_elencos[
    (df_elencos['name'].str.contains('Charlton Heston', case=False)) &
    (df_elencos['n'] == 1) &
    (df_elencos['year'].between(1960, 1969))
]
heston_60s_sorted = heston_60s.sort_values('year', ascending=False)
print(heston_60s_sorted)

                            title  year             name   type  \
944074                 Number One  1969  Charlton Heston  actor   
944077         Planet of the Apes  1968  Charlton Heston  actor   
944050               Counterpoint  1967  Charlton Heston  actor   
944120                 Will Penny  1967  Charlton Heston  actor   
944066                   Khartoum  1966  Charlton Heston  actor   
944068               Major Dundee  1965  Charlton Heston  actor   
944085  The Agony and the Ecstasy  1965  Charlton Heston  actor   
944111               The War Lord  1965  Charlton Heston  actor   
944038          55 Days at Peking  1963  Charlton Heston  actor   
944052               Diamond Head  1962  Charlton Heston  actor   
944101  The Pigeon That Took Rome  1962  Charlton Heston  actor   
944102  The Pigeon That Took Rome  1962  Charlton Heston  actor   
944103  The Pigeon That Took Rome  1962  Charlton Heston  actor   
944054                     El Cid  1961  Charlton Heston  acto

In [62]:
atores_50s = df_elencos[
    (df_elencos['type'] == 'actor') &
    (df_elencos['year'].between(1950, 1959))
]
print(len(atores_50s))

153998


In [ ]:
atrizes_50s = df_elencos[
    (df_elencos['type'] == 'actress') &
    (df_elencos['year'].between(1950, 1959))
]